repos:

  # General Text + YAML Lint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: detect-private-key

  # Markdown lint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.23.1
    hooks:
      - id: markdownlint
