#!/bin/bash

#------------------------------------------------------------------------------
# Constants

VERSION=0.1.0

# Defaults
FIRST_COMMIT=`git log --reverse | head -n 1 | cut -d " " -f2`
OLD_TAG=`echo ${FIRST_COMMIT:0:7}`
NEW_TAG="HEAD"
MAX_COMMITS=20
NOTES_DIR="docs/notes"
RUN_FLAG="ListParams"
OUT_FILE="/dev/stdout"


COMMIT_STRIP="origin\t\| (push)\|\.git"
COMMIT_URL=`git remote -v | grep -E "origin.*push" | sed "s/$COMMIT_STRIP//g"`/"commit"
REPO_STRIP="origin\t\| (push)\|\.git\|https:\/\/github.com\/"
REPO=`git remote -v | grep -E "origin.*push" | sed "s/$REPO_STRIP//g"`

# Parse Tags
TAGS=`git tag | tr '\n' ' '`
ARR_TAGS=($FIRST_COMMIT $TAGS "HEAD")
NUM_TAGS=${#ARR_TAGS[@]}

# An obscure way to reverse a list
ARR_TAGS=(`for ((i=${NUM_TAGS}-1; i>=0; i--));  do echo ${ARR_TAGS[$i]}; done | tr '\n' ' '  `)

#------------------------------------------------------------------------------
# Retrieve the absolute path of the executing script
AbsPath()
{
  # Retrieve the scripts directory (absolute)
  autologs_dir="`dirname \"$0\"`"
  autologs_dir="`( cd \"$autologs_dir\" && pwd )`"
  if [ -z "$autologs_dir" ] ; then
    echo " Directory $autologs_dir is inaccessible"
    exit 1
  fi
  echo $autologs_dir
}

AUTOLOGS_DIR=`AbsPath`;

#------------------------------------------------------------------------------
Help()
{
  # Display Help
  # Credits: https://opensource.com/article/19/12/help-bash-program
  # Display Help
  echo "Automatically create release notes and a changelog."
  echo
  echo "Syntax: autologs [-h|-v|-o|--old-tag|--new-tag|--max-commits|--notes-dir|--commits|--release]"
  echo
  echo "Options:"
  echo -e "\t-h, --help        Print this Help."
  echo -e "\t-v, --version     Print software version and exit."
  echo -e "\t-o, --output      Output file.                                [ default:" $OUT_FILE "]"
  echo -e "\t--old-tag         An earlier tag/commit hash to compare to.   [ default:" $OLD_TAG "]"
  echo -e "\t--new-tag         A newer tag/commit hash to compare to.      [ default:" $NEW_TAG "]"
  echo -e "\t--max-commits     The maximum number of commits to print.     [ default:" $MAX_COMMITS "]"
  echo -e "\t--notes-dir       A directory containing manual notees.       [ default:" $NOTES_DIR "]"
  echo -e "\t--commits         Print commit history."
  echo -e "\t--release         Print release notes."
  echo -e "\t--changelog       Print changelog."
  echo
}

#------------------------------------------------------------------------------
Version()
{
  # Display Version
  echo "$VERSION"
}

#------------------------------------------------------------------------------
ListParams()
{
  echo
  echo -e "\tRepository:      $REPO"
  echo -e "\tCommit URL:      $COMMIT_URL"
  echo -e "\tOld tag:         $OLD_TAG"
  echo -e "\tNew tag:         $NEW_TAG"
  echo -e "\tMax Commits:     $MAX_COMMITS"
  echo -e "\tNotes Directory: $NOTES_DIR"
  echo -e "\tOutput File:     $OUT_FILE"
  echo -e "\tRun:             $RUN_FLAG"
  echo
}

#------------------------------------------------------------------------------
Commits()
{
  # Positional Params
  OLD_TAG=$1
  NEW_TAG=$2
  MAX_COMMITS=$3
  NOTES_DIR=$4

  # Counter for commits to print
  i_commit=0;

  git log --pretty=oneline --abbrev-commit ${OLD_TAG}..${NEW_TAG} | \
    while read line;
    do
      # Stop printing if max commits has been reached
      if [[ $i_commit -ge $MAX_COMMITS && $MAX_COMMITS != "all" ]]; then
        break
      fi
      hash=`echo $line | cut -d " " -f 1`
      msg=`echo $line | sed "s/$hash //g"`
      echo -e "* [\`\`\`$hash\`\`\`](${COMMIT_URL}/$hash) $msg"

      # Increment commit counter
      i_commit=`expr $i_commit + 1`
    done;
}

Release()
{
  # Positional Params
  OLD_TAG=$1
  NEW_TAG=$2
  MAX_COMMITS=$3
  NOTES_DIR=$4

  #------------------------------------------------------------------------------
  # Name of the new tag
  if [[ $NEW_TAG == "HEAD" ]]; then
    NEW_TAG_NAME="Development"
  else
    NEW_TAG_NAME="$NEW_TAG"
  fi

  #------------------------------------
  # Release Header
  echo "## ${NEW_TAG_NAME}"
  echo
  #------------------------------------
  # Notes Header

  target_notes=${NOTES_DIR}/Notes_${NEW_TAG_NAME}.md

  if [[ -f $target_notes ]]; then
    echo "### Notes"
    echo
    grep -r '[0-9]\. ' $target_notes
    echo
  fi

  #------------------------------------
  # Pull Requests Header

  # Retieve PR hashes
  arr_pr_commits=( `git ls-remote origin 'pull/*/head' | awk '{print substr($1,1,7)}' | tr '\n' ' ' ` )
  pr_id=( `git ls-remote origin 'pull/*/head' | cut -f 2 | cut -d "/" -f 3 | tr '\n' ' ' ` )
  num_pr=${#arr_pr_commits[@]}

  # Retrieve commit hashes (all)
  arr_new_tag_commits=($(Commits $OLD_TAG $NEW_TAG "all" $NOTES_DIR | cut -d '`' -f 4 | tr '\n' ' '))

  # Search for matching PRs
  tag_pr=""
  arr_tag_pr=()
  for commit in ${arr_new_tag_commits[@]}; do
    for ((i_pr=0; i_pr<num_pr; i_pr++)); do
      pr=${arr_pr_commits[$i_pr]}
      if [[ $pr == $commit ]]; then
        tag_pr=${pr_id[$i_pr]};
        arr_tag_pr=(${arr_tag_pr[@]} $tag_pr)
      fi;
    done
  done

  # If a pull request was found
  if [[ $tag_pr ]]; then
      echo "### Pull Requests"
      echo

    for pr in ${arr_tag_pr[@]}; do
      pr_title=`curl -s https://api.github.com/repos/${REPO}/pulls/$pr | grep -m 1 title | cut -d '"' -f 4 `
      echo "* [\`\`\`pull/${pr}\`\`\`](https://github.com/${REPO}/pull/${pr}) ${pr_title}"
    done
    echo
  fi

  #------------------------------------
  # Commits Header
  echo "### Commits"
  commits=`Commits ${OLD_TAG} ${NEW_TAG} ${MAX_COMMITS}`
  echo
  if [[ $commits ]]; then
    echo -e "$commits";
    echo
  fi
}

#------------------------------------------------------------------------------
Changelog()
{
  # Positional Params
  OLD_TAG=$1
  NEW_TAG=$2
  MAX_COMMITS=$3
  NOTES_DIR=$4

  #------------------------------------
  # Changelog Header
  echo -e "# CHANGELOG"
  echo

  #------------------------------------
  # Write updates
  prev_tag=${ARR_TAGS[0]}
  for ((i_tag=1; i_tag<${NUM_TAGS}; i_tag++));
  do
    # Parse the current tag
    cur_tag=${ARR_TAGS[$i_tag]}
    #echo "Comparing $cur_tag to $prev_tag"
    # Create release notes for the current tag
    Release ${cur_tag} ${prev_tag} "all" $NOTES_DIR
    prev_tag=$cur_tag
  done
}

#------------------------------------------------------------------------------
# Credits: https://medium.com/@Drew_Stokes/bash-argument-parsing-54f3b81a6a8f
PARAMS=""
while (( "$#" )); do
  case "$1" in

    # Help
    -h|--help)
      Help
      exit 1
      ;;

    # Version
    -v|--version)
      Version
      exit 1
      ;;

    # Output file
    -o|--output)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        OUT_FILE=$2
        shift
      else
        shift
      fi
      ;;

    # Old tag
    --old-tag)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        OLD_TAG=$2
        shift
      else
        shift
      fi
      ;;

    # New tag
    --new-tag)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        NEW_TAG=$2
        shift
      else
        shift
      fi
      ;;

    # Max commits
    --max-commits)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        MAX_COMMITS=$2
        shift
      else
        shift
      fi
      ;;

    # Notes Directory
    --notes-dir)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        NOTES_DIR=$2
        shift
      else
        shift
      fi
      ;;

    # Commit History
    --commits)
      RUN_FLAG="Commits"
      shift
      ;;

    # Release Notes
    --release)
      RUN_FLAG="Release"
      shift
      ;;

    # Release Notes
    --changelog)
      RUN_FLAG="Changelog"
      shift
      ;;

    # Unsupported Flags
    -*|--*=)
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
    # Position Parameters
    *)
      PARAMS="$PARAMS $1"
      shift
      ;;
  esac
done
# set positional arguments in their proper place
eval set -- "$PARAMS"

# If there are 0 tags, use first and HEAD
if [[ `git tag | wc -l` == '0' ]]; then
  OLD_TAG=$FIRST_COMMIT
  NEW_TAG="HEAD"
fi

# If old and new are the same because there is only one tag
if [[ $OLD_TAG == $NEW_TAG && `git tag | wc -l` == '1' ]]; then
  OLD_TAG=$FIRST_COMMIT
fi

# Rename and backup old output file if it exists
if [[ $OUT_FILE != "/dev/stdout" && -f $OUT_FILE ]]; then
  mv $OUT_FILE ${OUT_FILE}.bak
fi

$RUN_FLAG $OLD_TAG $NEW_TAG $MAX_COMMITS $NOTES_DIR > $OUT_FILE
